apiVersion: apps/v1
kind: Deployment
metadata:
  name: practica5
  labels:
    app: practica5
spec:
  selector:
    matchLabels:
      app: practica5
  replicas: 1
  template:
    metadata:
      labels:
        app: practica5
    spec:
      containers:
        - name: practica5
          image: practica5
          ports:
            - containerPort: 80
