apiVersion: v1
kind: Service
metadata:
  name: practica5
  labels:
     app: practica5
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30005
    protocol: TCP
  selector:
     app: practica5
