apiVersion: v1
kind: Service
metadata:
  name: practica6
  labels:
     app: practica6
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30006
    protocol: TCP
  selector:
     app: practica6
