apiVersion: v1
kind: Pod
metadata:
  name: on-failure
  labels:
    app: app1
spec:
  containers:
    - name: on-failure
      image: busybox
      command: ["sh", "-c", "echo Example of pod failing.  && exit 1"]
  restartPolicy: OnFailure
