apiVersion: apps/v1
kind: Deployment
metadata:
  name: practica2
  labels:
    app: practica2
spec:
  selector:
    matchLabels:
      app: practica2
  replicas: 2
  template:
    metadata:
      labels:
        app: practica2
    spec:
      containers:
        - name: practica2
          image: practica2
          ports:
            - containerPort: 80
